name: CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
      - name: Generate
        run: just ci-generate
      - name: Build
        run: just ci-build
      - name: Test
        run: just ci-test
      - name: Integration Test
        run: just ci-integration-test
